services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    container_name: Laravel
    ports:
      - 8000:8000
    volumes:
      - ./beer-app:/var/www/html
    networks:
      - fbi_van
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.31.16.1" # <-- REPLACE IP
      # in wsl run --> ip route show | grep default | awk '{print $3}' 
      # This return the ip for wsl's host
      # replace [WSL_HOST_IP] with the ip

      # This has to be done since the docker services are running in wsl

  db:
    image: postgres:18.0
    container_name: Postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: beer_app
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - fbi_van

volumes:
  pgdata:

networks:
  fbi_van:
